// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FindProvision.proto

package com.cg.grpc;

public interface FindProvisionOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cg.grpc.FindProvision)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 timestamp = 1;</code>
   */
  long getTimestamp();

  /**
   * <code>int32 page = 2;</code>
   */
  int getPage();

  /**
   * <code>int32 size = 3;</code>
   */
  int getSize();
}
