// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FindProvision.proto

package com.cg.grpc;

public interface GetPageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cg.grpc.GetPage)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
   */
  java.util.List<com.cg.grpc.GetResults> 
      getResultList();
  /**
   * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
   */
  com.cg.grpc.GetResults getResult(int index);
  /**
   * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
   */
  int getResultCount();
  /**
   * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
   */
  java.util.List<? extends com.cg.grpc.GetResultsOrBuilder> 
      getResultOrBuilderList();
  /**
   * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
   */
  com.cg.grpc.GetResultsOrBuilder getResultOrBuilder(
      int index);

  /**
   * <code>int32 totalelements = 2;</code>
   */
  int getTotalelements();
}
