// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FindProvision.proto

package com.cg.grpc;

/**
 * Protobuf type {@code com.cg.grpc.GetPage}
 */
public  final class GetPage extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.cg.grpc.GetPage)
    GetPageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetPage.newBuilder() to construct.
  private GetPage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetPage() {
    result_ = java.util.Collections.emptyList();
    totalelements_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetPage(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              result_ = new java.util.ArrayList<com.cg.grpc.GetResults>();
              mutable_bitField0_ |= 0x00000001;
            }
            result_.add(
                input.readMessage(com.cg.grpc.GetResults.parser(), extensionRegistry));
            break;
          }
          case 16: {

            totalelements_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        result_ = java.util.Collections.unmodifiableList(result_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cg.grpc.FindProvisionOuterClass.internal_static_com_cg_grpc_GetPage_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cg.grpc.FindProvisionOuterClass.internal_static_com_cg_grpc_GetPage_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cg.grpc.GetPage.class, com.cg.grpc.GetPage.Builder.class);
  }

  private int bitField0_;
  public static final int RESULT_FIELD_NUMBER = 1;
  private java.util.List<com.cg.grpc.GetResults> result_;
  /**
   * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
   */
  public java.util.List<com.cg.grpc.GetResults> getResultList() {
    return result_;
  }
  /**
   * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
   */
  public java.util.List<? extends com.cg.grpc.GetResultsOrBuilder> 
      getResultOrBuilderList() {
    return result_;
  }
  /**
   * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
   */
  public int getResultCount() {
    return result_.size();
  }
  /**
   * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
   */
  public com.cg.grpc.GetResults getResult(int index) {
    return result_.get(index);
  }
  /**
   * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
   */
  public com.cg.grpc.GetResultsOrBuilder getResultOrBuilder(
      int index) {
    return result_.get(index);
  }

  public static final int TOTALELEMENTS_FIELD_NUMBER = 2;
  private int totalelements_;
  /**
   * <code>int32 totalelements = 2;</code>
   */
  public int getTotalelements() {
    return totalelements_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < result_.size(); i++) {
      output.writeMessage(1, result_.get(i));
    }
    if (totalelements_ != 0) {
      output.writeInt32(2, totalelements_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < result_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, result_.get(i));
    }
    if (totalelements_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, totalelements_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cg.grpc.GetPage)) {
      return super.equals(obj);
    }
    com.cg.grpc.GetPage other = (com.cg.grpc.GetPage) obj;

    boolean result = true;
    result = result && getResultList()
        .equals(other.getResultList());
    result = result && (getTotalelements()
        == other.getTotalelements());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getResultCount() > 0) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResultList().hashCode();
    }
    hash = (37 * hash) + TOTALELEMENTS_FIELD_NUMBER;
    hash = (53 * hash) + getTotalelements();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cg.grpc.GetPage parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.grpc.GetPage parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.grpc.GetPage parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.grpc.GetPage parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.grpc.GetPage parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.grpc.GetPage parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.grpc.GetPage parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.grpc.GetPage parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.grpc.GetPage parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cg.grpc.GetPage parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.grpc.GetPage parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.grpc.GetPage parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cg.grpc.GetPage prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.cg.grpc.GetPage}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.cg.grpc.GetPage)
      com.cg.grpc.GetPageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cg.grpc.FindProvisionOuterClass.internal_static_com_cg_grpc_GetPage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cg.grpc.FindProvisionOuterClass.internal_static_com_cg_grpc_GetPage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cg.grpc.GetPage.class, com.cg.grpc.GetPage.Builder.class);
    }

    // Construct using com.cg.grpc.GetPage.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getResultFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (resultBuilder_ == null) {
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        resultBuilder_.clear();
      }
      totalelements_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cg.grpc.FindProvisionOuterClass.internal_static_com_cg_grpc_GetPage_descriptor;
    }

    public com.cg.grpc.GetPage getDefaultInstanceForType() {
      return com.cg.grpc.GetPage.getDefaultInstance();
    }

    public com.cg.grpc.GetPage build() {
      com.cg.grpc.GetPage result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.cg.grpc.GetPage buildPartial() {
      com.cg.grpc.GetPage result = new com.cg.grpc.GetPage(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (resultBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          result_ = java.util.Collections.unmodifiableList(result_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.result_ = result_;
      } else {
        result.result_ = resultBuilder_.build();
      }
      result.totalelements_ = totalelements_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cg.grpc.GetPage) {
        return mergeFrom((com.cg.grpc.GetPage)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cg.grpc.GetPage other) {
      if (other == com.cg.grpc.GetPage.getDefaultInstance()) return this;
      if (resultBuilder_ == null) {
        if (!other.result_.isEmpty()) {
          if (result_.isEmpty()) {
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureResultIsMutable();
            result_.addAll(other.result_);
          }
          onChanged();
        }
      } else {
        if (!other.result_.isEmpty()) {
          if (resultBuilder_.isEmpty()) {
            resultBuilder_.dispose();
            resultBuilder_ = null;
            result_ = other.result_;
            bitField0_ = (bitField0_ & ~0x00000001);
            resultBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getResultFieldBuilder() : null;
          } else {
            resultBuilder_.addAllMessages(other.result_);
          }
        }
      }
      if (other.getTotalelements() != 0) {
        setTotalelements(other.getTotalelements());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cg.grpc.GetPage parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cg.grpc.GetPage) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<com.cg.grpc.GetResults> result_ =
      java.util.Collections.emptyList();
    private void ensureResultIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        result_ = new java.util.ArrayList<com.cg.grpc.GetResults>(result_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cg.grpc.GetResults, com.cg.grpc.GetResults.Builder, com.cg.grpc.GetResultsOrBuilder> resultBuilder_;

    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public java.util.List<com.cg.grpc.GetResults> getResultList() {
      if (resultBuilder_ == null) {
        return java.util.Collections.unmodifiableList(result_);
      } else {
        return resultBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public int getResultCount() {
      if (resultBuilder_ == null) {
        return result_.size();
      } else {
        return resultBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public com.cg.grpc.GetResults getResult(int index) {
      if (resultBuilder_ == null) {
        return result_.get(index);
      } else {
        return resultBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public Builder setResult(
        int index, com.cg.grpc.GetResults value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.set(index, value);
        onChanged();
      } else {
        resultBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public Builder setResult(
        int index, com.cg.grpc.GetResults.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.set(index, builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public Builder addResult(com.cg.grpc.GetResults value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.add(value);
        onChanged();
      } else {
        resultBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public Builder addResult(
        int index, com.cg.grpc.GetResults value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureResultIsMutable();
        result_.add(index, value);
        onChanged();
      } else {
        resultBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public Builder addResult(
        com.cg.grpc.GetResults.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.add(builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public Builder addResult(
        int index, com.cg.grpc.GetResults.Builder builderForValue) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.add(index, builderForValue.build());
        onChanged();
      } else {
        resultBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public Builder addAllResult(
        java.lang.Iterable<? extends com.cg.grpc.GetResults> values) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, result_);
        onChanged();
      } else {
        resultBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        result_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        resultBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public Builder removeResult(int index) {
      if (resultBuilder_ == null) {
        ensureResultIsMutable();
        result_.remove(index);
        onChanged();
      } else {
        resultBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public com.cg.grpc.GetResults.Builder getResultBuilder(
        int index) {
      return getResultFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public com.cg.grpc.GetResultsOrBuilder getResultOrBuilder(
        int index) {
      if (resultBuilder_ == null) {
        return result_.get(index);  } else {
        return resultBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public java.util.List<? extends com.cg.grpc.GetResultsOrBuilder> 
         getResultOrBuilderList() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(result_);
      }
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public com.cg.grpc.GetResults.Builder addResultBuilder() {
      return getResultFieldBuilder().addBuilder(
          com.cg.grpc.GetResults.getDefaultInstance());
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public com.cg.grpc.GetResults.Builder addResultBuilder(
        int index) {
      return getResultFieldBuilder().addBuilder(
          index, com.cg.grpc.GetResults.getDefaultInstance());
    }
    /**
     * <code>repeated .com.cg.grpc.GetResults result = 1;</code>
     */
    public java.util.List<com.cg.grpc.GetResults.Builder> 
         getResultBuilderList() {
      return getResultFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        com.cg.grpc.GetResults, com.cg.grpc.GetResults.Builder, com.cg.grpc.GetResultsOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            com.cg.grpc.GetResults, com.cg.grpc.GetResults.Builder, com.cg.grpc.GetResultsOrBuilder>(
                result_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }

    private int totalelements_ ;
    /**
     * <code>int32 totalelements = 2;</code>
     */
    public int getTotalelements() {
      return totalelements_;
    }
    /**
     * <code>int32 totalelements = 2;</code>
     */
    public Builder setTotalelements(int value) {
      
      totalelements_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 totalelements = 2;</code>
     */
    public Builder clearTotalelements() {
      
      totalelements_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.cg.grpc.GetPage)
  }

  // @@protoc_insertion_point(class_scope:com.cg.grpc.GetPage)
  private static final com.cg.grpc.GetPage DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cg.grpc.GetPage();
  }

  public static com.cg.grpc.GetPage getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetPage>
      PARSER = new com.google.protobuf.AbstractParser<GetPage>() {
    public GetPage parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetPage(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetPage> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetPage> getParserForType() {
    return PARSER;
  }

  public com.cg.grpc.GetPage getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

