// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FindProvision.proto

package com.cg.grpc;

/**
 * Protobuf type {@code com.cg.grpc.GetResults}
 */
public  final class GetResults extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:com.cg.grpc.GetResults)
    GetResultsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use GetResults.newBuilder() to construct.
  private GetResults(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private GetResults() {
    codigo_ = "";
    codSocieded_ = "";
    timestamp_ = 0L;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private GetResults(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            codigo_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            codSocieded_ = s;
            break;
          }
          case 24: {

            timestamp_ = input.readInt64();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.cg.grpc.FindProvisionOuterClass.internal_static_com_cg_grpc_GetResults_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.cg.grpc.FindProvisionOuterClass.internal_static_com_cg_grpc_GetResults_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.cg.grpc.GetResults.class, com.cg.grpc.GetResults.Builder.class);
  }

  public static final int CODIGO_FIELD_NUMBER = 1;
  private volatile java.lang.Object codigo_;
  /**
   * <code>string codigo = 1;</code>
   */
  public java.lang.String getCodigo() {
    java.lang.Object ref = codigo_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      codigo_ = s;
      return s;
    }
  }
  /**
   * <code>string codigo = 1;</code>
   */
  public com.google.protobuf.ByteString
      getCodigoBytes() {
    java.lang.Object ref = codigo_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      codigo_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int COD_SOCIEDED_FIELD_NUMBER = 2;
  private volatile java.lang.Object codSocieded_;
  /**
   * <code>string cod_socieded = 2;</code>
   */
  public java.lang.String getCodSocieded() {
    java.lang.Object ref = codSocieded_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      codSocieded_ = s;
      return s;
    }
  }
  /**
   * <code>string cod_socieded = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCodSociededBytes() {
    java.lang.Object ref = codSocieded_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      codSocieded_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TIMESTAMP_FIELD_NUMBER = 3;
  private long timestamp_;
  /**
   * <code>int64 timestamp = 3;</code>
   */
  public long getTimestamp() {
    return timestamp_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getCodigoBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, codigo_);
    }
    if (!getCodSociededBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, codSocieded_);
    }
    if (timestamp_ != 0L) {
      output.writeInt64(3, timestamp_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getCodigoBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, codigo_);
    }
    if (!getCodSociededBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, codSocieded_);
    }
    if (timestamp_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(3, timestamp_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.cg.grpc.GetResults)) {
      return super.equals(obj);
    }
    com.cg.grpc.GetResults other = (com.cg.grpc.GetResults) obj;

    boolean result = true;
    result = result && getCodigo()
        .equals(other.getCodigo());
    result = result && getCodSocieded()
        .equals(other.getCodSocieded());
    result = result && (getTimestamp()
        == other.getTimestamp());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + CODIGO_FIELD_NUMBER;
    hash = (53 * hash) + getCodigo().hashCode();
    hash = (37 * hash) + COD_SOCIEDED_FIELD_NUMBER;
    hash = (53 * hash) + getCodSocieded().hashCode();
    hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getTimestamp());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.cg.grpc.GetResults parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.grpc.GetResults parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.grpc.GetResults parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.grpc.GetResults parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.grpc.GetResults parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.cg.grpc.GetResults parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.cg.grpc.GetResults parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.grpc.GetResults parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.grpc.GetResults parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.cg.grpc.GetResults parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.cg.grpc.GetResults parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.cg.grpc.GetResults parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.cg.grpc.GetResults prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code com.cg.grpc.GetResults}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:com.cg.grpc.GetResults)
      com.cg.grpc.GetResultsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.cg.grpc.FindProvisionOuterClass.internal_static_com_cg_grpc_GetResults_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.cg.grpc.FindProvisionOuterClass.internal_static_com_cg_grpc_GetResults_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.cg.grpc.GetResults.class, com.cg.grpc.GetResults.Builder.class);
    }

    // Construct using com.cg.grpc.GetResults.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      codigo_ = "";

      codSocieded_ = "";

      timestamp_ = 0L;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.cg.grpc.FindProvisionOuterClass.internal_static_com_cg_grpc_GetResults_descriptor;
    }

    public com.cg.grpc.GetResults getDefaultInstanceForType() {
      return com.cg.grpc.GetResults.getDefaultInstance();
    }

    public com.cg.grpc.GetResults build() {
      com.cg.grpc.GetResults result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.cg.grpc.GetResults buildPartial() {
      com.cg.grpc.GetResults result = new com.cg.grpc.GetResults(this);
      result.codigo_ = codigo_;
      result.codSocieded_ = codSocieded_;
      result.timestamp_ = timestamp_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.cg.grpc.GetResults) {
        return mergeFrom((com.cg.grpc.GetResults)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.cg.grpc.GetResults other) {
      if (other == com.cg.grpc.GetResults.getDefaultInstance()) return this;
      if (!other.getCodigo().isEmpty()) {
        codigo_ = other.codigo_;
        onChanged();
      }
      if (!other.getCodSocieded().isEmpty()) {
        codSocieded_ = other.codSocieded_;
        onChanged();
      }
      if (other.getTimestamp() != 0L) {
        setTimestamp(other.getTimestamp());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.cg.grpc.GetResults parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.cg.grpc.GetResults) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object codigo_ = "";
    /**
     * <code>string codigo = 1;</code>
     */
    public java.lang.String getCodigo() {
      java.lang.Object ref = codigo_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codigo_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string codigo = 1;</code>
     */
    public com.google.protobuf.ByteString
        getCodigoBytes() {
      java.lang.Object ref = codigo_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codigo_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string codigo = 1;</code>
     */
    public Builder setCodigo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codigo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string codigo = 1;</code>
     */
    public Builder clearCodigo() {
      
      codigo_ = getDefaultInstance().getCodigo();
      onChanged();
      return this;
    }
    /**
     * <code>string codigo = 1;</code>
     */
    public Builder setCodigoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codigo_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object codSocieded_ = "";
    /**
     * <code>string cod_socieded = 2;</code>
     */
    public java.lang.String getCodSocieded() {
      java.lang.Object ref = codSocieded_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        codSocieded_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string cod_socieded = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCodSociededBytes() {
      java.lang.Object ref = codSocieded_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        codSocieded_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string cod_socieded = 2;</code>
     */
    public Builder setCodSocieded(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      codSocieded_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string cod_socieded = 2;</code>
     */
    public Builder clearCodSocieded() {
      
      codSocieded_ = getDefaultInstance().getCodSocieded();
      onChanged();
      return this;
    }
    /**
     * <code>string cod_socieded = 2;</code>
     */
    public Builder setCodSociededBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      codSocieded_ = value;
      onChanged();
      return this;
    }

    private long timestamp_ ;
    /**
     * <code>int64 timestamp = 3;</code>
     */
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 3;</code>
     */
    public Builder setTimestamp(long value) {
      
      timestamp_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 timestamp = 3;</code>
     */
    public Builder clearTimestamp() {
      
      timestamp_ = 0L;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:com.cg.grpc.GetResults)
  }

  // @@protoc_insertion_point(class_scope:com.cg.grpc.GetResults)
  private static final com.cg.grpc.GetResults DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.cg.grpc.GetResults();
  }

  public static com.cg.grpc.GetResults getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<GetResults>
      PARSER = new com.google.protobuf.AbstractParser<GetResults>() {
    public GetResults parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new GetResults(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<GetResults> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<GetResults> getParserForType() {
    return PARSER;
  }

  public com.cg.grpc.GetResults getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

