// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FindProvision.proto

package com.cg.grpc;

public interface GetResultsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:com.cg.grpc.GetResults)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string codigo = 1;</code>
   */
  java.lang.String getCodigo();
  /**
   * <code>string codigo = 1;</code>
   */
  com.google.protobuf.ByteString
      getCodigoBytes();

  /**
   * <code>string cod_socieded = 2;</code>
   */
  java.lang.String getCodSocieded();
  /**
   * <code>string cod_socieded = 2;</code>
   */
  com.google.protobuf.ByteString
      getCodSociededBytes();

  /**
   * <code>int64 timestamp = 3;</code>
   */
  long getTimestamp();
}
